### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by ckcollab** [ckcollab/tpaka#1]
# Todo
- [x] ~~Pick some colors~~ Black and white, maybe american flag red white and blue
- [ ] Put logo on site (can you get a high res logo from Trevor?)
- [x] ~~ANY high res pictures~~ We grabbed some and katie will take more
- [ ] Put some text on site to test it out (can just use Lorem Ipsum if unsure)
- [ ] Make google calendar integration for events (we add whatever events, website displays them nicely: tournaments, classes, seminars, etc.)
- [ ] Mock up some marketing pages (tournament, seminar, classes, childrens, adult, nerdy, health focused, path to blue belt)
- [ ] Instructor page
- [ ] About page
- [ ] Contact Us page
- [x] Setup a heroku for it
- [ ] Setup sendgrid to send emails (contact us form) to some email we setup for aka
- [ ] Test site on phone
- [ ] Forward domain
- [ ] Setup static site (just use Heroku PHP?)
- [ ] Setup cloudflare CDN
- [ ] Take a sweet ass picture of the front of AKA https://www.artofjiujitsu.com/trial-class/
- [ ] Carousel at the top
- [ ] Picture of the red doors to the back room
- [ ] Get homestead password ??? at least tpaka password, like godaddy or something
- [ ] AKA "red" accent in top black bar will make everything pop better
- [ ] Great pictures of each instructor
# Places to connect to
- [ ] Checkmat
- [ ] Guerilla jiu jitsu
- [ ] AKA
- [ ] AKA Thailand
- [ ] San Jose
# Instructor stuff
- [ ] Dyton
  https://www.youtube.com/watch?v=CVZNl4W9F0U
# References
- [ ] http://www.guerrillajiujitsu.com
- [ ] https://www.artofjiujitsu.com
- [ ] http://www.orbjj.com/
- [ ] http://americankickboxingacademy.com/
- [ ] https://akathailand.com/
- [ ] http://www.checkmatbjj.com/
# People need contacting
- [ ] mrs.erickson@aol.com wanted her son to try kids classes
# Cool graphic styles

![image](https://cloud.githubusercontent.com/assets/2185159/18227293/504d21e0-71d4-11e6-9443-3957e26feffa.png)
